version: "3.7"
services:

  # Snapshot MySQL instance
  redis:
    image: docker.io/bitnami/redis:7.0.5
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
networks:
  default:
    name: snapshot-network
