extend type Mutation {
  submitByte(submissionInput: ByteSubmissionInput!): ByteSubmission!
}

type ByteSubmission {
  id: String!
  created: String!
  createdBy: String!
  byteId: String!
  spaceId: String!
}

input ByteSubmissionInput {
  from: String!
  byteId: String!
  space: String!
  timestamp: String
  uuid: String!
}
