extend type Query {
  byteCollections(spaceId: String!): [ByteCollection!]!
  byteCollection(spaceId: String!, byteCollectionId: String!): ByteCollection!
}

extend type Mutation {
  createByteCollection(input: CreateByteCollectionInput!): ByteCollection!
  updateByteCollection(input: UpdateByteCollectionInput!): ByteCollection!
  deleteByteCollection(byteCollectionId: String!): Boolean!
}

type ByteCollection {
  id: ID!
  name: String!
  description: String!
  byteIds: [String!]!
  bytes: [ByteCollectionByte!]!
  status: String!
  priority: Int!
  videoUrl: String
  aspectRatio: String
}

type ByteCollectionByte {
  byteId: String!
  name: String!
  content: String!
  videoUrl: String
}

input CreateByteCollectionInput {
  name: String!
  description: String!
  spaceId: String!
  byteIds: [String!]!
  status: String!
  priority: Int!
  videoUrl: String
  aspectRatio: String
}

input UpdateByteCollectionInput {
  byteCollectionId: String!
  name: String!
  description: String!
  spaceId: String!
  byteIds: [String!]!
  status: String!
  priority: Int!
  videoUrl: String
  aspectRatio: String
}

enum AspectRatio {
  Landscape
  Portrait
}