extend type Query {
  byte(spaceId: String!, byteId: String!, includeDraft: Boolean): Byte!
  bytes(spaceId: String!): [Byte!]!
  byteSocialShare(spaceId: String!, byteId: String!): ByteSocialShare
}

extend type Mutation {
  upsertByte(spaceId: String!, input: UpsertByteInput!): Byte!
  saveByte(spaceId: String!, input: UpsertByteInput!): Byte!
  publishByte(spaceId: String!, input: UpsertByteInput!): Byte!
  generateSharablePdf(spaceId: String!, byteId: String!): String!
  upsertByteSocialShare(spaceId: String!, input: UpsertByteSocialShareInput!): ByteSocialShare!
}

type Byte {
  postSubmissionStepContent: String
  content: String!
  created: String!
  id: String!
  name: String!
  visibility: String
  publishStatus: String!
  showIncorrectOnCompletion: Boolean!
  steps: [ByteStep!]!
  admins: [String!]!
  tags: [String!]!
  priority: Int!
}

type ByteQuestion {
  answerKeys: [String!]!
  choices: [QuestionChoice!]!
  content: String!
  type: String!
  uuid: String!
  explanation: String!
}

type ByteUserInput {
  label: String!
  type: String!
  required: Boolean!
  uuid: String!
}

union ByteStepItem = ByteQuestion | ByteUserInput | UserDiscordConnect

type ByteStep {
  content: String!
  name: String!
  stepItems: [ByteStepItem!]!
  uuid: String!
}


type ByteLinkedinPdfContentStep {
  content: String!
  name: String!
}

type ByteLinkedinPdfContent {
  title: String!
  excerpt: String!
  steps: [ByteLinkedinPdfContentStep!]!
}

type ByteSocialShare {
  uuid: String!
  byteId: String!
  spaceId: String!
  linkedinPdfContent: ByteLinkedinPdfContent
  linkedInImages: [String!]
  linkedInPdf: String
  twitterImage: String
}


input ByteStepInput {
  content: String!
  name: String!
  stepItems: [StepItemInputGenericInput!]!
  uuid: String!
}

input UpsertByteInput {
  content: String!
  id: String!
  name: String!
  steps: [ByteStepInput!]!
  publishStatus: String!
  visibility: String
  thumbnail: String
  admins: [String!]!
  tags: [String!]!
  priority: Int!
  created: String!
}

input ByteLinkedinPdfContentStepInput {
  content: String!
  name: String!
}

input ByteLinkedinPdfContentInput {
  title: String!
  excerpt: String!
  steps: [ByteLinkedinPdfContentStepInput!]!
}

input UpsertByteSocialShareInput {
  uuid: String!
  byteId: String!
  spaceId: String!
  linkedinPdfContent: ByteLinkedinPdfContentInput
  linkedInImages: [String!]
  linkedInPdf: String
  twitterImage: String
}
