type OpenAIChoiceLogprobs {
  tokens: [String!]
  token_logprobs: [Float!]
  top_logprobs: [Any!]
  text_offset: [Int!]
  text: String
}

type CreateCompletionResponseChoice {
  finish_reason: String
  index: Int
  text: String
  logprobs: OpenAIChoiceLogprobs
}


type OpenAIUsage {
  prompt_tokens: Int!
  completion_tokens: Int!
  total_tokens: Int!
}

type OpenAICompletionResponse {
  id: ID!
  object: String!
  created: Int!
  model: String!
  usage: OpenAIUsage
  choices: [CreateCompletionResponseChoice!]!
}

type OpenAIChatCompletionChoice {
  message: OpenAIMessage
  finish_reason: String
  index: Int
}

type OpenAIMessage {
  role: String!
  content: String!
}


type OpenAIChatCompletionResponse {
  id: ID!
  object: String!
  created: Int!
  model: String!
  usage: OpenAIUsage
  choices: [OpenAIChatCompletionChoice!]!
}



enum  ChatCompletionRequestMessageRoleEnum {
  system
  user
  assistant
}

extend type Query {
  askChatCompletionAI(messages: [OpenAIChatMessageInput!]!): OpenAIChatCompletionResponse!
  askCompletionAI(prompt: String!): OpenAICompletionResponse!
}


input OpenAIChatMessageInput {
  role: ChatCompletionRequestMessageRoleEnum!
  content: String!
}
