extend type Query {
  project(id: String!): Project!
  projects(type: String): [Project!]!
  projectByte(projectId: String!, projectByteId: String!): ProjectByte!
  projectBytes(projectId: String!): [ProjectByte!]!
  projectByteCollections(projectId: String!): [ProjectByteCollection!]!
  projectByteCollection(projectId: String!, byteCollectionId: String!): ProjectByteCollection!

  projectShortVideo(projectId: String!, projectByteId: String!): ProjectShortVideo!
  projectShortVideos(projectId: String!): [ProjectShortVideo!]!
}

extend type Mutation {
  upsertProject(input: UpsertProjectInput!): Project!
  upsertProjectByte(projectId: String!, input: UpsertProjectByteInput!): ProjectByte!
  upsertProjectByteCollection(projectId: String!, input: UpsertProjectByteCollectionInput!): ProjectByteCollection!
  upsertProjectShortVideo(projectId: String!, shortVideo: ProjectShortVideoInput!): ProjectShortVideo!
}

type Project {
  id: String!
  admins: [String!]!
  adminUsernames: [String!]!
  adminUsernamesV1: [UsernameAndName!]!
  logo: String
  creator: String!
  name: String!
  details: String!
  website: String
  docs: String
  discord: String
  telegram: String
  github: String
  type: String!
  cardThumbnail: String
}

input UpsertProjectInput {
  id: String!
  admins: [String!]!
  adminUsernames: [String!]!
  adminUsernamesV1: [UsernameAndNameInput!]!
  logo: String
  name: String!
  details: String!
  type: String!
  website: String
  docs: String
  discord: String
  telegram: String
  github: String
  cardThumbnail: String
}

type ProjectByte {
  postSubmissionStepContent: String
  content: String!
  created: String!
  id: String!
  name: String!
  steps: [ByteStep!]!
  admins: [String!]!
  tags: [String!]!
  priority: Int!
}

input UpsertProjectByteInput {
  content: String!
  id: String!
  name: String!
  steps: [ByteStepInput!]!
  thumbnail: String
  admins: [String!]!
  tags: [String!]!
  priority: Int!
  created: String!
}

type ProjectByteCollection {
  id: String!
  name: String!
  description: String!
  byteIds: [String!]!
  bytes: [ByteCollectionByte!]!
  status: String!
  order: Int!
}

input UpsertProjectByteCollectionInput {
  id: String!
  name: String!
  description: String!
  projectId: String!
  byteIds: [String!]!
  status: String!
  order: Int!
}

type ProjectShortVideo {
  id: ID!
  title: String!
  description: String!
  createdAt: String!
  updatedAt: String!
  videoUrl: String!
  priority: Int!
  thumbnail: String!
}

input ProjectShortVideoInput {
  id: ID!
  title: String!
  description: String!
  videoUrl: String!
  priority: Int!
  thumbnail: String!
}

type UsernameAndName {
  username: String!
  nameOfTheUser: String!
}

input UsernameAndNameInput {
  username: String!
  nameOfTheUser: String!
}
