scalar Any
scalar JSON
scalar JSONObject
scalar DateTimeISO

# Queries
type Query {
  _empty: String
}

type Mutation {
  _empty: String
}

enum OrderDirection {
  asc
  desc
}

type JwtResponse {
  jwt: String!
}


input DateTimeFilter {
  before: DateTimeISO
  after: DateTimeISO
}
