scalar Any
scalar JSON
scalar JSONObject
scalar DateTimeISO

# Queries
type Query

type Mutation

enum OrderDirection {
  asc
  desc
}

type JwtResponse {
  jwt: String!
}


input DateTimeFilter {
  before: DateTimeISO
  after: DateTimeISO
}
