extend type Query {
  space(id: String, domain: String): Space

  spaceDiscordGuild(spaceId: String!): Any

  spaces: [Space!]
}

extend type Mutation {
  createSpace(spaceInput: UpsertSpaceInput!): Space!

  updateSpace(spaceInput: UpsertSpaceInput!): Space!

  addDiscordCredentials(spaceId: String!, code: String!, redirectUri: String!): Space!

  upsertGnosisSafeWallets(spaceId: String!, wallets: [GnosisSafeWalletInput!]!): Space!

  upsertSpaceInviteLinks(spaceId: String!, spaceInviteArgs: SpaceInviteArgs!): Space!

  upsertProjectGalaxyAccessToken(spaceId: String!, accessToken: String!): Space!

  upsertSpaceFeatures(spaceId: String!, features: [String!]!): Space!

  upsertSpaceGitGuideRepositories(spaceId: String!, gitGuideRepositories: [SpaceGitRepositoryInput!]!): Space!

  upsertSpaceAcademyRepository(spaceId: String!, academyRepository: String!): Space!

  createSignedUrl(spaceId: String!, input: CreateSignedUrlInput!): String!
}

type Space {
  id: String!
  admins: [String!]!
  avatar: String
  creator: String!
  features: [String!]!
  name: String!
  skin: String!
  spaceIntegrations: SpaceIntegrations
  inviteLinks: SpaceInviteLinks
}

type SpaceIntegrations {
  discordGuildId: String
  projectGalaxyTokenLastFour: String
  gnosisSafeWallets: [GnosisSafeWallet!]
  gitGuideRepositories: [SpaceGitRepository!]
  academyRepository: String
}

type GnosisSafeWallet {
  id: String!
  chainId: Int!
  order: Int!
  tokenContractAddress: String!
  walletAddress: String!
  walletName: String!
}

type SpaceGitRepository {
  # github or gitlab
  gitRepoType: String
  authenticationToken: String
  repoUrl: String!
}

type SpaceFilters {
  minScore: Float
  onlyMembers: Boolean
}

type SpaceInviteLinks {
  discordInviteLink: String
  showAnimatedButtonForDiscord: Boolean
  telegramInviteLink: String
  showAnimatedButtonForTelegram: Boolean
}
input SpaceWhere {
  id: String
  id_in: [String]
}

input GnosisSafeWalletInput {
  id: String!
  chainId: Int!
  order: Int!
  tokenContractAddress: String!
  walletAddress: String!
  walletName: String!
}

input SpaceGitRepositoryInput {
  # github or gitlab
  gitRepoType: String

  authenticationToken: String

  repoUrl: String!
}

input SpaceInviteArgs {
  discordInviteLink: String
  showAnimatedButtonForDiscord: Boolean
  telegramInviteLink: String
  showAnimatedButtonForTelegram: Boolean
}

input CreateSignedUrlInput {
  imageType: String!
  contentType: String!
  objectId: String!
  name: String!
}


input  UpsertSpaceInput {
  id: String!
  admins: [String!]!
  avatar: String!
  creator: String!
  features: [String!]!
  name: String!
  skin: String!
  inviteLinks: SpaceInviteLinksInput!
  spaceIntegrations: SpaceIntegrationsInput!
}

input  SpaceIntegrationsInput {
  discordGuildId: String
  projectGalaxyTokenLastFour: String
  gnosisSafeWallets: [GnosisSafeWalletInput!]!
  gitGuideRepositories: [SpaceGitRepositoryInput!]!
  academyRepository: String
}

input  SpaceInviteLinksInput {
  discordInviteLink: String
  showAnimatedButtonForDiscord: Boolean
  telegramInviteLink: String
  showAnimatedButtonForTelegram: Boolean
}
