extend type Query {
  timeline(spaceId: String!, timelineId: String!): Timeline!
  timelines(spaceId: String!): [Timeline!]!
}

extend type Mutation {
  upsertTimeline(spaceId: String!, input: UpsertTimelineInput!): Timeline!
}

type Timeline {
  id: String!
  name: String!
  excerpt: String!
  content: String!
  thumbnail: String
  created: String!
  publishStatus: String!
  events: [TimelineEvent!]!
  admins: [String!]!
  tags: [String!]!
  priority: Int!
  timelineStyle: String
}

type TimelineEvent {
  title: String!
  uuid: String!
  date: DateTimeISO!
  summary: String!
  fullDetails: String
  moreLink: String
  order: Int!
}

input UpsertTimelineInput {
  id: String
  name: String!
  excerpt: String!
  content: String!
  thumbnail: String
  publishStatus: String!
  events: [UpsertTimelineEventInput!]!
  admins: [String!]!
  tags: [String!]!
  priority: Int!
  created: String!
  timelineStyle: String
}

input UpsertTimelineEventInput {
  title: String!
  uuid: String!
  date: DateTimeISO!
  summary: String!
  fullDetails: String
  moreLink: String
}
