extend type Query {
  projectShortVideo(projectId: String!, projectShortVideoId: String!): ProjectShortVideo!
  projectShortVideos(projectId: String!): [ProjectShortVideo!]!
}

extend type Mutation {
  upsertProjectShortVideo(projectId: String!, shortVideo: ProjectShortVideoInput!): ProjectShortVideo!
  updateArchivedStatusOfProjectShortVideo(projectId: String!, projectShortVideoId: String!, archived: Boolean!): ProjectShortVideo!
  updateSeoOfProjectShortVideo(projectId: String!, seoMeta: SEOMetaInput): ProjectShortVideo!
}

type ProjectShortVideo {
  id: ID!
  title: String!
  description: String!
  createdAt: String!
  updatedAt: String!
  videoUrl: String!
  priority: Int!
  thumbnail: String!
  archived: Boolean!
  seoMeta: SEOMeta
  archive: Boolean
}

input ProjectShortVideoInput {
  id: ID!
  title: String!
  description: String!
  videoUrl: String!
  priority: Int!
  thumbnail: String!
  seoMeta: SEOMetaInput
  archive: Boolean
}
