extend type Query {
  projectByte(projectId: String!, projectByteId: String!): ProjectByte!
  projectBytes(projectId: String!): [ProjectByte!]!
}

extend type Mutation {
  upsertProjectByte(projectId: String!, input: UpsertProjectByteInput!): ProjectByte!
  updateArchivedStatusOfProjectByte(projectId: String!, projectByteId: String!, archived: Boolean!): ProjectByte!
  updateSeoOfProjectByte(projectId: String!, seoMeta: SEOMetaInput): ProjectByte!
}

type ProjectByte {
  postSubmissionStepContent: String
  content: String!
  created: String!
  id: String!
  name: String!
  steps: [ByteStep!]!
  admins: [String!]!
  tags: [String!]!
  completionScreen: CompletionScreen
  priority: Int!
  archived: Boolean!
  seoMeta: SEOMeta
  videoUrl: String
  byteStyle: String
}

input UpsertProjectByteInput {
  content: String!
  id: String!
  name: String!
  steps: [ByteStepInput!]!
  thumbnail: String
  admins: [String!]!
  tags: [String!]!
  priority: Int!
  created: String!
  seoMeta: SEOMetaInput
  videoUrl: String
  byteStyle: String
}
