extend type Query {
  project(id: String!): Project!
  projects(type: String): [Project!]!
}

extend type Mutation {
  upsertProject(input: UpsertProjectInput!): Project!
  updateArchivedStatusOfProject(projectId: String!, archived: Boolean!): Project!
  updateSeoOfProject(projectId: String!, seoMeta: SEOMetaInput): Project!
}

type Project {
  id: String!
  admins: [String!]!
  adminUsernames: [String!]!
  adminUsernamesV1: [UsernameAndName!]!
  logo: String
  creator: String!
  name: String!
  details: String!
  excerpt: String!
  website: String
  docs: String
  discord: String
  telegram: String
  github: String
  type: String!
  cardThumbnail: String
  archived: Boolean!
  seoMeta: SEOMeta
}

input UpsertProjectInput {
  id: String!
  admins: [String!]!
  adminUsernames: [String!]!
  adminUsernamesV1: [UsernameAndNameInput!]!
  logo: String
  name: String!
  details: String!
  excerpt: String!
  type: String!
  website: String
  docs: String
  discord: String
  telegram: String
  github: String
  cardThumbnail: String
  seoMeta: SEOMetaInput
}
